#!/bin/bash
[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueConfig" && exit 1
[[ "$1" -eq "" ]] && echo "No ID Provided. Expected: hueOn <id>" && exit 1
echo "Turning light $1 on"
curl -s -XPUT $(cat ~/.HueControl/address)/api/$(cat ~/.HueControl/username)/lights/$1/state --data '{"on":true}' > /dev/null

exit 0
